package com.jxqm.jiangdou.model

/**
 * Created By bhx On 2019/9/29 0029 11:17
 */
data class JobSignModel(
    val address: String,
    val area: String,
    val areaCode: String,
    val arrival: String,
    val arrivalTime: Any,
    val contact: String,
    val content: String,
    val createTime: String,
    val datesJson: String,
    val email: String,
    val employerId: Int,
    val employerName: Any,
    val endTime: Any,
    val frozenDeposit: Any,
    val gender: String,
    val genderCode: Int,
    val id: Int,
    val invalid: Boolean,
    val jobTypeId: Int,
    val jobTypeName: String,
    val latitude: Double,
    val longitude: Double,
    val mapImg: String,
    val offer: String,
    val offerNum: Int, //
    val offerTime: String,
    val pageNo: Any,
    val pageSize: Any,
    val recruitNum: Int,
    val salary: Int,
    val settlement: String,
    val settlementTime: Any,
    val signNum: Int, //报名人数
    val signTime: String,
    val startTime: String,
    val status: String,
    val statusCode: Int,
    val tel: String,
    val timesJson: String,
    val title: String,
    val typeImg: String,
    val typeImgUrl: Any,
    val userId: Int
) : JobSignModelBase()

//{
//    "id": 13,
//    "pageNo": null,
//    "pageSize": null,
//    "userId": 3,
//    "employerId": 1,
//    "jobTypeId": 26,
//    "title": "哈哈啊哈爱",
//    "content": "啊来啊还哈KKK路考虑他来啦来两句来肉上几句天记录",
//    "salary": 36,
//    "genderCode": 2,
//    "gender": "不限",
//    "contact": "阿",
//    "tel": "19137629693",
//    "email": "2466921206@qq.com",
//    "address": "都摸头out摩托",
//    "latitude": 34.81912275548772,
//    "longitude": 113.57312492889685,
//    "statusCode": 2,
//    "status": "招聘中",
//    "areaCode": "郑州市,null",
//    "area": "郑州高新区创业中心",
//    "mapImg": "static/assert/upload/93398147-b964-4ce1-bae7-f29584f00bdb.png",
//    "typeImg": "/static/assets/images/canyin.png",
//    "recruitNum": 2,
//    "createTime": "2019.09.25 14:18",
//    "datesJson": "[\"2019-9-25\",\"2019-9-30\",\"2019-10-16\",\"2019-10-19\"]",
//    "timesJson": "[{\"start\":\"08 : 30\",\"end\":\"16 : 30\"},{\"start\":\"08 : 30\",\"end\":\"15 : 30\"}]",
//    "frozenDeposit": null,
//    "signNum": 10,
//    "offerNum": 3,
//    "startTime": "2019-10-11 13:13",
//    "endTime": null,
//    "employerName": null,
//    "jobTypeName": "服务员",
//    "typeImgUrl": null,
//    "offer": "已录用",
//    "offerTime": "2019-09-27 17:57",
//    "arrival": "未到岗",
//    "arrivalTime": null,
//    "settlement": "未结算",
//    "settlementTime": null,
//    "signTime": "2019-09-27 10:22",
//    "invalid": false
//}

